if: tag IS blank

language: node_js

node_js: 9

cache:
  directories:
    - node_modules

stages:
  - release

jobs:
  include:
    - stage: release
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
